name: wataru
favicon: null
layout_spectrum: 0.6615660723764449
typography_spectrum: 0.7402699438389391
title: wataru
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-73941685-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.044836715096607804
  lightness: 0.39089569239877164
  saturation: 0.6431409304495901
  rhythmicContrast: 0.9767254160251468
purpose: []
