name: wataru
favicon: null
layout_spectrum: 0.01165
typography_spectrum: 0.60046
title: wataru
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-73941685-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fefff7'
    - '#9e9bb0'
    - '#694623'
    - '#7f7065'
  brandStrength: 0.044836715096607804
  lightness: 0.0625
  saturation: 0.6431409304495901
  rhythmicContrast: 0.9767254160251468
purpose: []
